name: ApprovePr
on:
  pull_request:
    branches: [ "!main" ]
  workflow_dispatch:
jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Approve pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr review --approve
          gh pr merge --merge
