name: Simulate a releasy thing

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: live
    steps:
      - uses: actions/checkout@v3
      - name: Update version.txt
        env: 
          GH_TOKEN: ${{ secrets.APP_TOKEN }}
        run: |
          version=$(cat version.txt)
          echo $((version+1)) > version.txt
          echo "Written new version to file:"
          cat version.txt
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit -am "Increment version"
          git pull --ff-only
          git push origin
