name: Simulate a releasy thing

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: live
    steps:
      - uses: actions/checkout@v3
      - name: Update version.txt
        run: |
          version=$(cat version.txt)
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.APP_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/samblackburn/BranchProtectionTest/contents/version.txt \
            -d '{"message":"Auto bump version","committer":{"name":"Monalisa Octocat","email":"octocat@github.com"},"content":"$((version+1))"}'
